### PR TITLE
Be able to set domain name for ip - Idea

### PR DESCRIPTION
**Pull request by mrbusysky**

### CODE REVIEW

**Review by wakawakathedev — APPROVED** [review]
lgtm

**Comment by buckyroberts** [comment]
The migrations files themselves can't be updated since those were already ran on each node. Instead the model needs updated and then the files are generated with the `makemigration` command https://docs.djangoproject.com/en/3.2/ref/django-admin/#makemigrations

**Comment by buckyroberts** [comment]
@mrbusysky if you write up a ticket I can have @fonar look into it. This is quite involved as it touched quite a bit of the codebase (node initialization scripts, serialization validation, tests, etc...). It will also require changes across the shared repo here https://github.com/thenewboston-developers/thenewboston-python/blob/development/src/thenewboston/models/network_node.py#L12 since that's where both the Bank and Validator both pull from.

**Comment by mrbusysky** [comment]
pushed part of the fix for ip https://github.com/thenewboston-developers/thenewboston-python/pull/95

**Pull request closed without merging**
